### ISSUE TITLE
Return ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by pemudakoding** [unburn/greetify#4]
Hi Mate i try using the package and return me an error with typescript
![image](https://github.com/unburn/greetify/assets/62993054/a620043d-498a-46d7-92df-c69ace5c613a)

how to solve this issue ya?

**Comment by UnschooledGamer** [comment]
@pemudakoding Can provide the code you are using?

**Comment by flameface** [comment]
@pemudakoding the issue has been fixed, install the latest greetify version -> 2.0.1
