### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by JharlyOk** [unburn/greetify#6]
Hi, I have this error code when running my code on my VPS, I don't understand the reason, previously I was testing this library on my PC and I had no errors when running my bot and everything worked perfect, now when uploading and running my bot on my VPS I have this error. I am new to this and would like to know if anyone knows how to fix it.

**Comment by UnschooledGamer** [comment]
> Hi, I have this error code when running my code on my VPS, I don't understand the reason, previously I was testing this library on my PC and I had no errors when running my bot and everything worked perfect, now when uploading and running my bot on my VPS I have this error. I am new to this and would like to know if anyone knows how to fix it.

It means that the image or background that was being fetched by greetify returned 429 (too many requests) means it got rate limited.

**Comment by JharlyOk** [comment]
Thanks, I solved it, by the way, excellent library, I hope you can create something for a level system and level table, thanks.
